-- ============================================================================
-- Soldier Hub production rebuild split file
-- Run the numbered files in order in a brand-new empty Supabase project only.
-- ============================================================================

begin;

set check_function_bodies = off;
set search_path = public, extensions;

-- FUNCTIONS
CREATE OR REPLACE FUNCTION public.admin_list_profiles(p_queue text DEFAULT 'pending'::text, p_limit integer DEFAULT 50)
 RETURNS TABLE(id uuid, full_name text, email text, personal_email text, phone text, bio text, avatar_color text, avatar_url text, role text, status text, verification_status text, base text, created_at timestamp with time zone, updated_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
                                  declare
                                    v_queue text := lower(trim(coalesce(p_queue, 'pending')));
                                      v_limit integer := greatest(1, least(coalesce(p_limit, 50), 100));
                                      begin
                                        if auth.uid() is null then
                                            raise exception 'Please log in again before loading admin profiles.';
                                              end if;

                                                if not public.is_admin() then
                                                    raise exception 'Admin access is required to load profile queues.';
                                                      end if;

                                                        if v_queue not in ('pending', 'verified', 'blocked') then
                                                            raise exception 'Invalid admin profile queue.';
                                                              end if;

                                                                return query
                                                                  select
                                                                      p.id,
                                                                          p.full_name,
                                                                              p.email,
                                                                                  p.personal_email,
                                                                                      p.phone,
                                                                                          p.bio,
                                                                                              p.avatar_color,
                                                                                                  p.avatar_url,
                                                                                                      p.role,
                                                                                                          p.status,
                                                                                                              p.verification_status,
                                                                                                                  p.base,
                                                                                                                      p.created_at,
                                                                                                                          p.updated_at
                                                                                                                            from public.profiles p
                                                                                                                              where
                                                                                                                                  (v_queue = 'pending' and p.status = 'pending')
                                                                                                                                      or (v_queue = 'verified' and p.status = 'verified')
                                                                                                                                          or (v_queue = 'blocked' and p.status in ('rejected', 'revoked'))
                                                                                                                                            order by p.created_at desc, p.id desc
                                                                                                                                              limit v_limit;
                                                                                                                                              end;
                                                                                                                                              $function$;


CREATE OR REPLACE FUNCTION public.admin_reject_profile(p_profile_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.is_admin() then
    raise exception 'Only admins can reject profiles.';
  end if;

  update public.profiles
  set
    status = 'rejected',
    verification_status = 'rejected',
    updated_at = now()
  where id = p_profile_id
    and status = 'pending'
    and verification_status = 'pending';
end;
$function$;


CREATE OR REPLACE FUNCTION public.admin_revoke_profile(p_profile_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.is_admin() then
    raise exception 'Only admins can revoke profiles.';
  end if;

  update public.profiles
  set
    status = 'revoked',
    verification_status = 'revoked',
    updated_at = now()
  where id = p_profile_id
    and status = 'verified'
    and verification_status = 'verified';
end;
$function$;


CREATE OR REPLACE FUNCTION public.admin_revoke_profile_by_email(p_email text)
 RETURNS TABLE(id uuid, email text, personal_email text, full_name text, status text, verification_status text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.is_admin() then
    raise exception 'Only admins can revoke profiles.';
  end if;

  return query
  update public.profiles
  set
    status = 'revoked',
    verification_status = 'revoked'
  where (
      lower(coalesce(profiles.email, profiles.personal_email)) = lower(p_email)
      or lower(profiles.personal_email) = lower(p_email)
    )
    and coalesce(profiles.role, 'user') <> 'admin'
  returning
    profiles.id,
    profiles.email,
    profiles.personal_email,
    profiles.full_name,
    profiles.status,
    profiles.verification_status;
end;
$function$;


CREATE OR REPLACE FUNCTION public.admin_verify_profile_by_email(p_email text)
 RETURNS TABLE(id uuid, email text, personal_email text, full_name text, status text, verification_status text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.is_admin() then
    raise exception 'Only admins can verify profiles.';
  end if;

  return query
  update public.profiles
  set
    status = 'verified',
    verification_status = 'verified'
  where lower(coalesce(profiles.email, profiles.personal_email)) = lower(p_email)
     or lower(profiles.personal_email) = lower(p_email)
  returning
    profiles.id,
    profiles.email,
    profiles.personal_email,
    profiles.full_name,
    profiles.status,
    profiles.verification_status;
end;
$function$;


CREATE OR REPLACE FUNCTION public.count_post_reports(p_post_id uuid)
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    coalesce((select count(*) from public.reports r where r.post_id = p_post_id), 0)
    +
    coalesce((select count(*) from public.visitor_reports vr where vr.post_id = p_post_id), 0);
$function$;


CREATE OR REPLACE FUNCTION public.create_comment_safe(p_post_id uuid, p_body text)
 RETURNS TABLE(id uuid, comment_id uuid, post_id uuid, body text, created_at timestamp with time zone, author_id uuid, author_user_id uuid, author_name_cached text, author_color_cached text, author_avatar_url text, author_avatar_url_cached text, profile_avatar_url text, avatar_url text, is_anonymous_author boolean, viewer_is_author boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          DECLARE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            v_user_id uuid := auth.uid();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v_comment_id uuid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF v_user_id IS NULL THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    RAISE EXCEPTION 'You must be logged in to comment.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        IF NOT EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SELECT 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FROM public.profiles p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE p.id = v_user_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          AND COALESCE(p.status, p.verification_status, 'pending') = 'verified'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RAISE EXCEPTION 'Your profile must be verified before you can comment.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    IF p_post_id IS NULL THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        RAISE EXCEPTION 'Post was not identified.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            IF p_body IS NULL OR LENGTH(TRIM(p_body)) = 0 THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RAISE EXCEPTION 'Please write a comment before posting.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    IF LENGTH(TRIM(p_body)) > 2000 THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        RAISE EXCEPTION 'Comment must be 2000 characters or less.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO public.comments (post_id, author_id, body)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              VALUES (p_post_id, v_user_id, TRIM(p_body))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RETURNING comments.id INTO v_comment_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  RETURN QUERY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT gc.*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FROM public.get_public_comments_for_post(p_post_id, 100) gc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WHERE gc.id = v_comment_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $function$;


CREATE OR REPLACE FUNCTION public.create_follow_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      declare
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        v_actor_name text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        begin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if new.follower_id is null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               or new.following_id is null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or new.follower_id = new.following_id then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          end if;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            select coalesce(p.full_name, 'Someone')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              into v_actor_name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from public.profiles p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  where p.id = new.follower_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insert into public.notifications (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        recipient_user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            actor_user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actor_name_cached,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        post_title_cached,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            read,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    values (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new.following_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            new.follower_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                coalesce(v_actor_name, 'Someone'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'follow',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'followed your profile',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    on conflict do nothing;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      update public.notifications
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        set
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            read = false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actor_name_cached = coalesce(v_actor_name, 'Someone'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    post_title_cached = 'followed your profile',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        created_at = now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          where recipient_user_id = new.following_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              and actor_user_id = new.follower_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  and type = 'follow';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $function$;

set check_function_bodies = on;

commit;
