-- TOMBSTONE / DEPRECATED BOARD PREP MIGRATION
--
-- This file is intentionally retired.
-- Do not add executable SQL here.
--
-- Reason:
--   This older Board Prep migration used outdated ACFT-era questions and
--   difficulty values that no longer match the production Board Prep schema.
--   The active Board Prep source is:
--     20260606223000_board_prep_admin_requests_and_seed.sql
--     20260606233000_board_prep_admin_questions_and_requests.sql
--
-- There are intentionally no executable SQL statements in this file.
